### ISSUE TITLE
Fresh setup with Node not working

### ISSUE THREAD

**Issue by john-griffin** [yusukebe/hono-remix-adapter#34]
Followed the instructions in the readme to setup the adapter on a fresh Remix app with Node. Running gets the following error:

```
Error: Cannot find module '@remix-run/cloudflare' imported from '/home/projects/remix-run-remix-yigbsg/node_modules/hono-remix-adapter/dist/dev.js'
    at nodeImport (file:///home/projects/remix-run-remix-yigbsg/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:53096:19)
    at ssrImport (file:///home/projects/remix-run-remix-yigbsg/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52963:22)
    at ssrDynamicImport (file:///home/projects/remix-run-remix-yigbsg/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52988:12)
    at Array.eval (/home/projects/remix-run-remix-yigbsg/node_modules/hono-remix-adapter/dist/dev.js:41:44)
    at _hono_node_server.getRequestListener.overrideGlobalObjects (file:///home/projects/remix-run-remix-yigbsg/node_modules/@hono/vite-dev-server/dist/dev-server.js:109:32)
    at responseViaResponseObject (file:///home/projects/remix-run-remix-yigbsg/node_modules/@hono/node-server/dist/index.mjs:351:15) {
  code: 'ERR_MODULE_NOT_FOUND'
```

Please see reproduction here. https://stackblitz.com/edit/remix-run-remix-yigbsg?file=server%2Findex.ts

**Comment by Code-Hex** [comment]
@john-griffin I think you can resolve this issue just install `@remix-run/cloudflare`
