### ISSUE TITLE
404 Not Found with useFetcher in only local

### ISSUE THREAD

**Issue by Code-Hex** [yusukebe/hono-remix-adapter#40]
Only in the local environment, a request using useFetcher to a resource route that only defines a loader will result in a 404 Not Found.

No error:

- hono-remix-adapter is not used.
- production build and hono-remix-adapter is used.

```
Error: No route matches URL "/src/app/routes/user.tsx"
    at getInternalRouterError (/Users/codehex/go/src/github.com/Code-Hex/remix-test-fetch/node_modules/@remix-run/router/router.ts:5505:5)
    at Object.query (/Users/codehex/go/src/github.com/Code-Hex/remix-test-fetch/node_modules/@remix-run/router/router.ts:3527:19)
    at handleDocumentRequest (/Users/codehex/go/src/github.com/Code-Hex/remix-test-fetch/node_modules/@remix-run/server-runtime/dist/server.js:275:35)
    at requestHandler (/Users/codehex/go/src/github.com/Code-Hex/remix-test-fetch/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getRequestListener.overrideGlobalObjects (file:///Users/codehex/go/src/github.com/Code-Hex/remix-test-fetch/node_modules/@hono/vite-dev-server/dist/dev-server.js:93:32)
    at responseViaResponseObject (file:///Users/codehex/go/src/github.com/Code-Hex/remix-test-fetch/node_modules/@hono/node-server/dist/index.mjs:333:15)
No routes matched location "/src/app/routes/user.tsx?import"
ErrorResponseImpl {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/src/app/routes/user.tsx"',
  error: Error: No route matches URL "/src/app/routes/user.tsx"
      at getInternalRouterError (/Users/codehex/go/src/github.com/Code-Hex/remix-test-fetch/node_modules/@remix-run/router/router.ts:5505:5)
      at Object.query (/Users/codehex/go/src/github.com/Code-Hex/remix-test-fetch/node_modules/@remix-run/router/router.ts:3527:19)
      at handleDocumentRequest (/Users/codehex/go/src/github.com/Code-Hex/remix-test-fetch/node_modules/@remix-run/server-runtime/dist/server.js:275:35)
      at requestHandler (/Users/codehex/go/src/github.com/Code-Hex/remix-test-fetch/node_modules/@remix-run/server-runtime/dist/server.js:160:24)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at getRequestListener.overrideGlobalObjects (file:///Users/codehex/go/src/github.com/Code-Hex/remix-test-fetch/node_modules/@hono/vite-dev-server/dist/dev-server.js:93:32)
      at responseViaResponseObject (file:///Users/codehex/go/src/github.com/Code-Hex/remix-test-fetch/node_modules/@hono/node-server/dist/index.mjs:333:15)
}
```

I have reproduction code for this:

https://github.com/Code-Hex/remix-test-fetch

**Comment by Code-Hex** [comment]
Oh, I have probably found a solution, but I honestly don't know why this works.

```diff
diff --git a/vite.config.ts b/vite.config.ts
index 14620e0..2c2f3be 100644
--- a/vite.config.ts
+++ b/vite.config.ts
@@ -7,6 +7,7 @@ import tsconfigPaths from "vite-tsconfig-paths";
 import serverAdapter from "hono-remix-adapter/vite";
 import { getLoadContext } from "./src/load-context";
 import adapter from "@hono/vite-dev-server/cloudflare";
+import { defaultOptions } from "@hono/vite-dev-server";

 declare module "@remix-run/node" {
   interface Future {
@@ -31,6 +32,12 @@ export default defineConfig({
       adapter,
       getLoadContext,
       entry: "src/api/index.ts",
+      exclude: [
+        ...defaultOptions.exclude,
+        "/assets/**",
+        "/app/**",
+        "/src/app/**",
+      ],
     }),
     tsconfigPaths(),
   ],
```

If this was the intended specification for hono-remix-adapter and not a particular problem, it could be closed.

**Comment by yusukebe** [comment]
Hi @Code-Hex 

This is not a bug, so you can resolve the issue with the setting as you showed. But it's not helpful, so I've added the change to exclude `/src/app/**` by default. https://github.com/yusukebe/hono-remix-adapter/pull/41 With the new version, you don't have to change the setting to `vite.config.ts`.

**Comment by Code-Hex** [comment]
@yusukebe Thank you so much!
